# Generated by Django 3.1.2 on 2020-10-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='alias',
            new_name='publisher',
        ),
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(max_length=160),
        ),
    ]
